### PR TITLE
Added support for biblatex/biber

### PR DESCRIPTION
**Pull request by djt308**
Bibtex is default, but biblatex/biber can be used by specifying USE_BIBLATEX in CMakeLists.txt.

### CODE REVIEW

**Comment by kmorel** [comment]
The implementation is not quite right. The change is replacing ```BIBTEX_COMPILER``` with ```BIB_COMPILER``` and setting that in the ```latex_setup_variables``` function to either ```bibtex``` or ```biber``` depending on the value of ```LATEX_USE_BIBTEX```. The problem is that ```LATEX_USE_BIBTEX``` is not valid in the scope of the ```latex_setup_variables``` function. It should only be used while in ```add_latex_document``` or problems can ensue.

A safer implementation would be to keep ```BIBTEX_COMPILER``` and add a separate ```BIBER_COMPILER``` so you find them both. (Likewise for the compiler flags.) Then use a condition in ```add_latex_targets_internal``` to choose one based on ```LATEX_USE_BIBTEX```, which should be valid at that point.

**Comment by djt308** [comment]
Thanks for the feedback. In older versions I originally had it completely separate, similar to how you describe, but decided to refactor it because I thought there was a lot of repeated code. I'll change it back then resubmit it.

**Comment by djt308** [comment]
Hopefully this looks a little better.

**Comment by kmorel** [comment]
This looks good. I added a few minor changes before merging in. The biggest change was renaming the ```BIBLATEX_COMPILER``` variable to ```BIBER_COMPILER``` to be consistent with the ```FindLATEX``` package.

**Comment by djt308** [comment]
Okay, thanks. I didn't think about the `FindLATEX` package.

**Comment by kmorel** [comment]
Yeah. ```UseLATEX``` uses ```FindLATEX``` under the covers to find the locations of the all the LaTeX executables, so the latter chooses the names of those CMake variables.

**Pull request merged**
